FROM node:alpine

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV REACT_APP_API_KEY=${REACT_APP_API_KEY}
ENV REACT_APP_AUTH_DOMAIN=${REACT_APP_AUTH_DOMAIN}
ENV REACT_APP_DATABASE_URL=${REACT_APP_DATABASE_URL}
ENV REACT_APP_PROJECT_ID=${REACT_APP_PROJECT_ID}
ENV REACT_APP_STORAGE_BUCKET=${REACT_APP_STORAGE_BUCKET}
ENV REACT_APP_MESSAGING_SENDER_ID=${REACT_APP_MESSAGING_SENDER_ID}
ENV REACT_APP_APP_ID=${REACT_APP_APP_ID}
ENV REACT_APP_MEASUREMENT_ID=${REACT_APP_MEASUREMENT_ID}
RUN npm run build
